<a href="https://colab.research.google.com/github/Musfirah-Ansari/ML-DAY2-Assignment/blob/main/MLDAY2Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***ML DAY 2 Assignment By "MUSFIRAH FAYYAZ"***

### Create a program to simulate and analyze the temperature readings of a month. The program should:
### Generate random daily temperature values for 30 days, ranging from 15°C to 35°C.
### Calculate the average, maximum, and minimum temperatures for the entire month.
### Identify the number of days when the temperature exceeds 30°C (considered as hot days).
### Determine the hottest day of the month, based on the highest temperature recorded.
###Reshape the daily temperatures into weekly data for better analysis (consider 4 weeks with 7 days each).
### Calculate the total temperature and average temperature for each week.

# ***Monthly Temperature Tracker and Analyzer***

> *Welcome to The "Climate Insights: Monthly Temperature Simulation and Analysis*

In [89]:
# ML DAY 2 Assignment By "MUSFIRAH FAYYAZ"

import numpy as np

In [90]:
monthDays = 30
dailyTemperatureReadings = np.random.uniform(15, 35, monthDays)
print("Daily Temperature Readings (°C) for the Month:\n")
for i, temp in enumerate(dailyTemperatureReadings, 1):
    print(f"Day {i}: {temp:.2f}°C")

Daily Temperature Readings (°C) for the Month:

Day 1: 31.10°C
Day 2: 26.82°C
Day 3: 24.58°C
Day 4: 31.09°C
Day 5: 34.42°C
Day 6: 23.00°C
Day 7: 18.86°C
Day 8: 32.95°C
Day 9: 18.65°C
Day 10: 20.62°C
Day 11: 17.78°C
Day 12: 30.52°C
Day 13: 30.66°C
Day 14: 34.05°C
Day 15: 16.96°C
Day 16: 28.32°C
Day 17: 20.81°C
Day 18: 25.12°C
Day 19: 25.29°C
Day 20: 33.04°C
Day 21: 22.82°C
Day 22: 25.71°C
Day 23: 29.44°C
Day 24: 20.08°C
Day 25: 28.87°C
Day 26: 32.90°C
Day 27: 29.07°C
Day 28: 34.77°C
Day 29: 32.28°C
Day 30: 22.73°C


In [91]:
averageTemperature = np.mean(dailyTemperatureReadings)
maximumTemperature = np.max(dailyTemperatureReadings)
minimumTemperature = np.min(dailyTemperatureReadings)

print("\n--- Temperature Summary for the Month ---\n")
print(f"Average Temperature for the month: {averageTemperature:.2f}°C")
print(f"Maximum Temperature for the month: {maximumTemperature:.2f}°C")
print(f"Minimum Temperature for the month: {minimumTemperature:.2f}°C")



--- Temperature Summary for the Month ---

Average Temperature for the month: 26.78°C
Maximum Temperature for the month: 34.77°C
Minimum Temperature for the month: 16.96°C


In [92]:
hotDays = np.sum(dailyTemperatureReadings > 30)

print("\n------------------ Hot Days Summary --------------------\n")
print(f"Number of Hot Days (Days with temperature > 30°C): {hotDays} days")



------------------ Hot Days Summary --------------------

Number of Hot Days (Days with temperature > 30°C): 11 days


In [93]:
hottestDayNumber = np.argmax(dailyTemperatureReadings)
hottestDayTemperature = dailyTemperatureReadings[hottestDayNumber]

print("\n----------- Hottest Day Summary ------------\n")
print(f"Hottest Day Temperature: {hottestDayTemperature:.2f}°C on Day {hottestDayNumber + 1}")



----------- Hottest Day Summary ------------

Hottest Day Temperature: 34.77°C on Day 28


In [94]:
#weeklyTemperatureReadings = dailyTemperatureReadings.reshape(4, 7)

weeklyTemperatureReadings = dailyTemperatureReadings.reshape(5, 6)

print("\n------------ Reshaping Daily Temperatures into Weekly Data -------------\n")
print("Temperature readings for each week (5 weeks, 6 days each):\n")
print(weeklyTemperatureReadings)



------------ Reshaping Daily Temperatures into Weekly Data -------------

Temperature readings for each week (5 weeks, 6 days each):

[[31.10256042 26.81567118 24.58143167 31.09371238 34.42375097 23.00169438]
 [18.85850464 32.95322994 18.65463236 20.62173446 17.77604784 30.51937874]
 [30.65696917 34.05155535 16.95682981 28.3186945  20.80569368 25.1179921 ]
 [25.29250514 33.04472546 22.82432224 25.70685956 29.44454893 20.07529504]
 [28.86506036 32.89846616 29.06693173 34.76763537 32.27753136 22.73020098]]


In [95]:
totalTemperatureWeekly = np.sum(weeklyTemperatureReadings, axis=1)

print("\n--- Weekly Temperature Totals ---\n")
print("Total Temperature for Each Week:\n")
for i, total in enumerate(totalTemperatureWeekly, 1):
    print(f"Week {i}: Total Temperature = {total:.2f}°C")



--- Weekly Temperature Totals ---

Total Temperature for Each Week:

Week 1: Total Temperature = 171.02°C
Week 2: Total Temperature = 139.38°C
Week 3: Total Temperature = 155.91°C
Week 4: Total Temperature = 156.39°C
Week 5: Total Temperature = 180.61°C


In [96]:
averageTemperatureWeekly = np.mean(weeklyTemperatureReadings, axis=1)

print("\n--- Weekly Average Temperature ---")
print("Average Temperature for Each Week:\n")
for i, avg in enumerate(averageTemperatureWeekly, 1):
    print(f"Week {i}: Average Temperature = {avg:.2f}°C")



--- Weekly Average Temperature ---
Average Temperature for Each Week:

Week 1: Average Temperature = 28.50°C
Week 2: Average Temperature = 23.23°C
Week 3: Average Temperature = 25.98°C
Week 4: Average Temperature = 26.06°C
Week 5: Average Temperature = 30.10°C


In [97]:
print("\n--- WEEKLY DATA ANALYSIS ---\n")
for week_number in range(4):
    print(f"Week #{week_number + 1} 🗓️:")
    print(f"  Total Temperature 🌡️ = {totalTemperatureWeekly[week_number]:.2f}°C")
    print(f"  Average Temperature 🌞 = {averageTemperatureWeekly[week_number]:.2f}°C\n")



--- WEEKLY DATA ANALYSIS ---

Week #1 🗓️:
  Total Temperature 🌡️ = 171.02°C
  Average Temperature 🌞 = 28.50°C

Week #2 🗓️:
  Total Temperature 🌡️ = 139.38°C
  Average Temperature 🌞 = 23.23°C

Week #3 🗓️:
  Total Temperature 🌡️ = 155.91°C
  Average Temperature 🌞 = 25.98°C

Week #4 🗓️:
  Total Temperature 🌡️ = 156.39°C
  Average Temperature 🌞 = 26.06°C

